# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='SecureObjectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_key', models.BinaryField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='django_securebox.SecureObject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSecureBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_user_key', models.BinaryField(db_column='user_key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secure_box', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='secureobjectlink',
            unique_together=set([('user', 'name')]),
        ),
    ]
